### ISSUE TITLE
[v0.7.0] Release Tracker

### ISSUE THREAD

**Issue by khirotaka** [khirotaka/enchanter#109]
# Release v0.7.0

## New Features
* [x] #103 AMP training.
* [x] #104 Migrating from setup.py to poetry
* [x] #119 Support TensorFlow Dataset
* [x] #121 Context API
* [x] #126 Network Visualizer using Netron

## API Changes
* [x] #107 change module name `wrappers` -> `tasks`
* [x] `enchanter.addons.layers.CausalConv1d`

## Bug Fix
* [x] #106 A ZeroDivisionError on `SELayer`

## Other
* [x] #105 Closing GitHub Pages
